[package]
name = "tablet-ui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tablet-ui"
path = "src/main.rs"

[dependencies]
directories = "6.0.0"
eframe = { version = "0.34.3", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
egui = "0.34.3"
egui_plot = "0.35.0"
serde = { version = "1.0.228", features = ["derive"] }
tablet-consumer = { path = "../tablet-consumer" }
tablet-core = { path = "../tablet-core" }
tablet-process = { path = "../tablet-process" }
tablet-stream = { path = "../tablet-stream" }
toml = "1.1.2"
